### ISSUE TITLE
website?

### ISSUE THREAD

**Issue by mpadge** [m-clark/exploratory-data-analysis-tools#1]
Hi Michael, While duly acknowledging that you are evidently actively working on this repo right now, I was just wondering what your plans might be for serving the associated pages? I ask because I'm currently working on rOpenSci's project for [peer review of statistical software](https://ropenscilabs.github.io/statistical-software-peer-review/index.html), and would like to link to a hosted site of this repo as a really good overview of EDA software. No worries if you're not planning to do so for a while yet, but if you could please ping via this issue, then i'll know when it might be up, and hopefully be able to link from that time point on. Thanks for the great work!

**Comment by m-clark** [comment]
Howdy! It's actually up at https://m-clark.github.io/exploratory-data-analysis-tools/, and mostly complete (my workshop is tomorrow), so feel free to link that, as I don't expect it to change. The article that prompted me to explore the tools in the first place is found here: https://journal.r-project.org/archive/2019/RJ-2019-033/index.html, and talks about other packages I don't cover.  

I'll add a link to the ReadMe as well.

**Comment by mpadge** [comment]
Awesome, thanks a lot! Good luck with the workshop! And yes, I had seen the article, which was actually what first led me to your repo. But for what my subjective opinion is worth, you do a much better job of both exploring and illustrating what the differences are, hence my desire to link your site as well as the article :+1:
